# Copyright Gary Guo.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "klint"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rusqlite = { version = "0.34.0", features = ["bundled"] }
home = "0.5.11"

[dev-dependencies]
compiletest_rs = { version = "0.11.2", features = ["tmp"] }

[package.metadata.rust-analyzer]
# This crate uses #![feature(rustc_private)]
rustc_private = true

[lints.clippy]
